// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.Models;

#nullable disable

namespace ProjectName.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20260501011153_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ProjectName.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_year");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_date");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_date");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("VIN");

                    b.ToTable("vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
